apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairi-case-dev
  namespace: development
  labels:
    app: fairi-case-dev
    tier: backend
spec:
  selector:
      matchLabels:
        app: fairi-case-dev
        service: fairi-case-svc-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: fairi-case-dev
        service: fairi-case-svc-dev
    spec:
      containers:
        - name: fairi-case-dev
          image: 904440666777.dkr.ecr.us-east-1.amazonaws.com/jenkins-pipeline-demo3:dev_${BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
              
-------

apiVersion: v1
kind: Service
metadata:
  name: fairi-case-svc-dev
  namespace: development
  labels:
    service: fairi-case-svc-dev
spec:
  type: NodePort
  selector:
    app: fairi-case-dev
    service: fairi-case-svc-dev
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8083
      targetPort: http
      protocol: TCP
      name: http


                                                                                                                               47,1          Bot

                                                                                    
