apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pipeline-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: jenkins-pipeline-demo
    spec:
      containers:
      - name: jenkins-pipeline-demo
        image: 904440666777.dkr.ecr.us-east-1.amazonaws.com/jenkins-pipeline-demo
        ports:
        - containerPort: 8080
