apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: 904440666777.dkr.ecr.us-east-1.amazonaws.com/jenkins-pipeline-demo
        ports:
        - containerPort: 8080
